## Inport Packages

In [1]:
import pandas as pd
import numpy as np

## Load Data

In [6]:
asd_all = pd.read_csv('/Users/markzepeda/Desktop/Final Project/R Github Projects/ASD_FINAL/asd_all_ML.csv')

## Data Wrangling

### Recode Sex, Jaundice, Family_ASD

In [7]:
cleanup = {"Sex": {"m": 0, "f": 1},
          "Jaundice": {"no": 0, "yes": 1},
          "Family_ASD": {"no": 0, "yes": 1},
          "Class": {"NO": 0, "YES": 1}}

In [12]:
asd_all.replace(cleanup, inplace=True)

### Dummy Code Ethnicity

In [17]:
EthnicityDummy = pd.get_dummies(asd_all['Ethnicity'],drop_first=True)
asd_all = pd.concat([asd_all, EthnicityDummy],axis=1)
asd_all.drop(['Ethnicity'], axis=1, inplace=True)

## Random Forest

## 'Class'

### Import Packages

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [38]:
x = asd_all.drop('Class', axis=1)
y = asd_all['Class']

### Train Test Split

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=76)

### Initial Random Forest Model

In [40]:
forest = RandomForestClassifier(n_estimators=500, random_state=76)
forest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=76, verbose=0,
                       warm_start=False)

### Assess the Model

In [41]:
forestPredictions = forest.predict(x_test)
print(confusion_matrix(y_test, forestPredictions))
print(classification_report(y_test, forestPredictions))

[[341  12]
 [  7 203]]
              precision    recall  f1-score   support

           0       0.98      0.97      0.97       353
           1       0.94      0.97      0.96       210

    accuracy                           0.97       563
   macro avg       0.96      0.97      0.96       563
weighted avg       0.97      0.97      0.97       563



In [42]:
print(confusion_matrix(y_test, forestPredictions))

[[341  12]
 [  7 203]]


## 'Jaundice' Random Forest Model

In [43]:
x = asd_all.drop('Jaundice', axis=1)
y = asd_all['Jaundice']

In [44]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=76)

In [142]:
forest = RandomForestClassifier(n_estimators=500, random_state=76)
forest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=76, verbose=0,
                       warm_start=False)

### Evaluate Model

In [143]:
forestPredictions = forest.predict(x_test)
print(confusion_matrix(y_test, forestPredictions))
print(classification_report(y_test, forestPredictions))

[[463  11]
 [ 80   9]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91       474
           1       0.45      0.10      0.17        89

    accuracy                           0.84       563
   macro avg       0.65      0.54      0.54       563
weighted avg       0.79      0.84      0.79       563



In [144]:
print(confusion_matrix(y_test, forestPredictions))

[[463  11]
 [ 80   9]]
